-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."user"
(
    user_id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    email character varying(50) NOT NULL,
    phone character varying(20) NOT NULL,
    date_registration timestamp with time zone NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.friendship
(
    "user_id1,user_id2" integer NOT NULL,
    status character varying(20) NOT NULL,
    date date NOT NULL,
    user_id1 integer NOT NULL,
    user_id2 integer NOT NULL,
    PRIMARY KEY ("user_id1,user_id2")
);

CREATE TABLE IF NOT EXISTS public.workout
(
    workout_id integer NOT NULL,
    type_workout character varying(50) NOT NULL,
    PRIMARY KEY (workout_id)
);

CREATE TABLE IF NOT EXISTS public."health metrics"
(
    metrics_id integer NOT NULL,
    steps integer NOT NULL,
    pulse integer NOT NULL,
    calories integer NOT NULL,
    measurement_date timestamp with time zone NOT NULL,
    user_workout_id integer NOT NULL,
    PRIMARY KEY (metrics_id),
    UNIQUE (user_workout_id)
);

CREATE TABLE IF NOT EXISTS public.user_workout
(
    user_user_id integer NOT NULL,
    workout_workout_id integer NOT NULL,
    user_workout_id integer NOT NULL,
    date date NOT NULL,
    "time" time with time zone NOT NULL,
    PRIMARY KEY (user_workout_id)
);

ALTER TABLE IF EXISTS public.friendship
    ADD FOREIGN KEY (user_id1)
    REFERENCES public."user" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.friendship
    ADD FOREIGN KEY (user_id2)
    REFERENCES public."user" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."health metrics"
    ADD FOREIGN KEY (user_workout_id)
    REFERENCES public.user_workout (user_workout_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.user_workout
    ADD FOREIGN KEY (user_user_id)
    REFERENCES public."user" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.user_workout
    ADD FOREIGN KEY (workout_workout_id)
    REFERENCES public.workout (workout_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;